// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_pDV7XVs7wQ3aNb5-yLu0bkJccMI2-ZA',
    appId: '1:418346769493:web:bf40b086198663fac0c8dc',
    messagingSenderId: '418346769493',
    projectId: 'act12-4708c',
    authDomain: 'act12-4708c.firebaseapp.com',
    storageBucket: 'act12-4708c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeInIuL6ForAcyDvZmGAIvlhYa4DySirI',
    appId: '1:418346769493:android:184717e816821d85c0c8dc',
    messagingSenderId: '418346769493',
    projectId: 'act12-4708c',
    storageBucket: 'act12-4708c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1rPrv17SKoVgEoYJtFo6PzMXo46Q3Axc',
    appId: '1:418346769493:ios:0b566db3f8c30458c0c8dc',
    messagingSenderId: '418346769493',
    projectId: 'act12-4708c',
    storageBucket: 'act12-4708c.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAct12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1rPrv17SKoVgEoYJtFo6PzMXo46Q3Axc',
    appId: '1:418346769493:ios:0b566db3f8c30458c0c8dc',
    messagingSenderId: '418346769493',
    projectId: 'act12-4708c',
    storageBucket: 'act12-4708c.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAct12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_pDV7XVs7wQ3aNb5-yLu0bkJccMI2-ZA',
    appId: '1:418346769493:web:b48343b33d757db3c0c8dc',
    messagingSenderId: '418346769493',
    projectId: 'act12-4708c',
    authDomain: 'act12-4708c.firebaseapp.com',
    storageBucket: 'act12-4708c.firebasestorage.app',
  );
}
